# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'empresas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for empresas
  pod 'RxCocoa', '~> 3.0.0'
  pod 'Moya-ModelMapper/RxSwift', '~> 4.1.0'
  pod 'RxOptional'
  pod 'RxSwiftUtilities', :git => 'https://github.com/RxSwiftCommunity/RxSwiftUtilities.git'
  pod 'SwiftyUserDefaults'

  target 'empresasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'empresasUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
